[pytest]
filterwarnings =
    # aiohttp.BasicAuth is deprecated, but proxy_auth still requires it.
    # Keep BasicAuth because header-based proxy auth fails for HTTPS connections.
    # See issue #151.
    ignore:BasicAuth is deprecated and will be removed in aiohttp 4\.0:DeprecationWarning
